# Please write a function named word_generator(characters: str, length: int, amount: int) which returns a new generator for generating random words based on the parameters given.

# A random word is generated by selecting from the string named characters as many characters as is indicated by the argument length. The same character can appear many times in a random word.

# The generator returns as many words as specified by the argument amount before terminating.

# An example run of the word generator:

# wordgen = word_generator("abcdefg", 3, 5)
# for word in wordgen:
#     print(word)
# Sample output
# dbf
# baf
# ead
# fga
# ccc

# NB: it is up to you how you implement this function. You may use a "traditional" generator or a generator comprehension equally well.

from random import randint


def word_generator(characters: str, length: int, amount: int):
    for i in range(amount):
        word = ''
        for j in range(length):
            word += characters[randint(0, len(characters)-1)]
        yield word

if __name__ == '__main__':
    wordgen = word_generator("abcdefg", 3, 5)
    for word in wordgen:
        print(word)